numpy module

In [2]:
import numpy as np

In [7]:
a1d = np.array([1,2,3,4])
a1d

array([1, 2, 3, 4])

In [9]:
a2d = np.array([[1,2],[3,4]])
a2d

array([[1, 2],
       [3, 4]])

In [10]:
a3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
a3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

dtype

In [11]:
a = np.array([127,128,129,260])
a

array([127, 128, 129, 260])

In [13]:
a = np.array([127,128,129,260],dtype=np.int8)
a

C:\Users\Morteza\AppData\Local\Temp\ipykernel_5732\3073442640.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 128 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  a = np.array([127,128,129,260],dtype=np.int8)
C:\Users\Morteza\AppData\Local\Temp\ipykernel_5732\3073442640.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 129 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  a = np.array([127,128,129,260],dtype=np.int8)
C:\Users\Morteza\AppData\Local\Temp\ipykernel_5732\3073442640.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 260 to int8 wi

array([ 127, -128, -127,    4], dtype=int8)

In [14]:
a = np.array([2,3,4],dtype=np.uint8)
a

array([2, 3, 4], dtype=uint8)

In [15]:
b = np.array([5,6,7],dtype=np.uint8)
b

array([5, 6, 7], dtype=uint8)

In [17]:
c_unsigned32 = a-b
c_unsigned32

array([253, 253, 253], dtype=uint8)

In [20]:
c_signed = a-b.astype(dtype=np.int32)
c_signed

array([-3, -3, -3])

In [21]:
c_signed.dtype

dtype('int32')

In [23]:
# arange method
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
#linspace method
np.linspace(1.,4.,7) # convert interval into 6 pieces

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [32]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
#create eye matrices
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [34]:
#create diagonal matrices
np.diag([1,2,10])

array([[ 1,  0,  0],
       [ 0,  2,  0],
       [ 0,  0, 10]])

In [35]:
np.diag([1,2,20],1)

array([[ 0,  1,  0,  0],
       [ 0,  0,  2,  0],
       [ 0,  0,  0, 20],
       [ 0,  0,  0,  0]])

In [43]:
#reshape mathod
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [44]:
#np.diag return the diagonal content of (a)
np.diag(a)

array([0, 4, 8])

In [45]:
np.diag(a,1)

array([1, 5])

In [3]:
# np.ones() method
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [51]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

numpy array are mutable.

In [55]:
a = np.array([1,2,3,4])
b=a[:2]
b

array([1, 2])

In [56]:
a+=1
a

array([2, 3, 4, 5])

In [57]:
b

array([2, 3])

In [63]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [64]:
b=a[:2]
b+=1
b

array([2, 3])

In [65]:
a #array a has changed, due to mutable

array([2, 3, 3, 4])

In [ ]:
# solution:
b = a[:2].b = a[:2].copy

In [67]:
# vstack and hhstack method
a = np.array([1,2,3,4])
b = np.array([0,5,6,7])
np.vstack((a,b))

array([[1, 2, 3, 4],
       [0, 5, 6, 7]])

In [68]:
np.hstack((a,b))

array([1, 2, 3, 4, 0, 5, 6, 7])

In [73]:
#split  , hsplit , vsplit method
z = np.arange(8)
np.split(z,4)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7])]

In [81]:
mat = np.arange(16).reshape((4,4))
mat

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [83]:
np.split(mat,2,axis=1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [88]:
np.hsplit(mat,2) #axis=0

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [92]:
np.vsplit(mat,3) #axis=1


ValueError: array split does not result in an equal division

compare array and List