# Linear Classification

## Initialization

In [65]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

## Data generation

In [66]:
np.random.seed(200)
N = 1000
X1 = np.hstack((2 + np.random.randn(N, 2), (np.ones((N, 1))))) #  داده دو بعدی ایجاد می کنیم. و یک ستون 1
X2 = np.hstack((3 + np.random.randn(N, 2), (np.ones((N, 1)))))
X = np.vstack((X1, X2))
y1, y2 = np.ones((N, 1)), -np.ones((N, 1))
y_train = np.vstack((y1, y2))
data_matrix = np.hstack((X, y_train))
X_test_1 = np.hstack((2 + np.random.randn(N, 2), (np.ones((N, 1)))))
X_test_2 = np.hstack((3 + np.random.randn(N, 2), (np.ones((N, 1)))))
X_test = np.vstack((X_test_1, X_test_2))
y1, y2 = np.ones((N, 1)), -np.ones((N, 1))
y_test = np.vstack((y1, y2))
print(np.mean(X1, axis=0))
print(np.mean(X2, axis=0))


[1.97227706 2.02505839 1.        ]
[2.94791075 2.97267458 1.        ]


## Perceptron


In [67]:
i = 0
lr = 0.01 #learning rate
w = np.ones(X1.shape[1]) # first estimation of W (dimension = X)
epoch = 200 #NUMBER OF ITTERATIONS
while i == 0 and epoch !=0 : # برای توقف یا باید همگرا بشیم یا تعداد دوره مون تموم بشه
    miss_classified = 0
    for item in range(len(data_matrix)): # data matrix = [X1,X2,1,y]
        x = data_matrix[item,:-1]
        y = data_matrix[item, -1]
        projection = np.dot(w, x)
        if y * projection > 0: #(tn*yn>0)
            continue
        else:
            w += lr * x * y # زیگما در دل این جمله هست.
            # we calculate lr*Xn*y for each X (that is missclass) and sum to obtain final W after first epoch.
            miss_classified += 1
    print('epoch {}'.format(200 - epoch + 1))
    print('miss classified {}'.format(miss_classified))
    epoch -=1
    if miss_classified == 0:
        i = 1






epoch 1
miss classified 49
epoch 2
miss classified 23
epoch 3
miss classified 22
epoch 4
miss classified 20
epoch 5
miss classified 17
epoch 6
miss classified 17
epoch 7
miss classified 15
epoch 8
miss classified 14
epoch 9
miss classified 12
epoch 10
miss classified 12
epoch 11
miss classified 10
epoch 12
miss classified 10
epoch 13
miss classified 10
epoch 14
miss classified 10
epoch 15
miss classified 10
epoch 16
miss classified 9
epoch 17
miss classified 8
epoch 18
miss classified 7
epoch 19
miss classified 7
epoch 20
miss classified 7
epoch 21
miss classified 7
epoch 22
miss classified 4
epoch 23
miss classified 5
epoch 24
miss classified 6
epoch 25
miss classified 6
epoch 26
miss classified 4
epoch 27
miss classified 6
epoch 28
miss classified 6
epoch 29
miss classified 4
epoch 30
miss classified 6
epoch 31
miss classified 6
epoch 32
miss classified 5
epoch 33
miss classified 6
epoch 34
miss classified 6
epoch 35
miss classified 4
epoch 36
miss classified 6
epoch 37
miss classifi

In [68]:
w

array([-0.04884905, -0.04560976,  0.04      ])

## Validation


In [69]:
y_pre = []
for i in range(len(X_test)):
    y_pre.append(np.sign(np.dot(w,X_test[i, ]))) #y_pre = sign(W * Xtest[i, :])

confusion_matrix(y_pre, y_test).T
# با اینکه همگرا نشدیم دقت مدلی که خودمون نوشتیم از پکیچ بهتره. به نظرم به خاطر شرط استاپ هستش.

array([[1000,    0],
       [ 988,   12]], dtype=int64)

## Using sklearn package

In [70]:
from sklearn.linear_model import Perceptron

model = Perceptron(tol=0.001 , random_state=0) #stop condition is tol = W1 - W0 until tol = 0.001
model.fit(X,y_train)

C:\Users\Morteza\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Perceptron()

In [71]:
y_pre = model.predict(X)
# python package crate y_pre in form of (-1,1)
# but for scartch code we must use sign method to tranform calculated dot(W,X) to y_pre=(-1,1).
print(confusion_matrix(y_pre, y_train).T)
model.coef_
# همه داده اموزش را نتوانسته که تفکیک کند

[[967  33]
 [737 263]]


array([[-8.00319581, -8.29277277, 13.        ]])

In [72]:
y_pre = model.predict(X_test)
print(confusion_matrix(y_pre, y_test).T)
model.coef_

[[979  21]
 [712 288]]


array([[-8.00319581, -8.29277277, 13.        ]])

## Least Square method

In [73]:
a = np.linalg.inv(np.dot(X.T, X)) # W = (X.T * X)^-1 * X.T * y
b = np.dot(X.T, y_train)
W = np.dot(a, b)
W

array([[-0.34750646],
       [-0.32445486],
       [ 1.6656679 ]])

In [74]:
y_pre = []
for i in range(len(X_test)):
    y_pre.append(np.sign(np.dot(w,X_test[i, ])))

confusion_matrix(y_pre, y_test).T

array([[1000,    0],
       [ 988,   12]], dtype=int64)

In [76]:
np.sign(np.dot(w,X_test[i, ]))

-1.0